apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing
  labels:
    app.kubernetes.io/instance: ticketing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: itsm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ticketing
      app.kubernetes.io/name: itsm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ticketing
        app.kubernetes.io/name: itsm
    spec:
      containers:
        - image: "{{ .Values.images.tags.ticketing }}"
          imagePullPolicy: IfNotPresent
          name: ticketing
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 9000
              name: grpc
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 1280Mi
            requests:
              cpu: 20m
              memory: 128Mi
          securityContext: { }
          volumeMounts:
            - mountPath: /ticketing/conf
              name: ticketing-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ticketing-config
          secret:
            defaultMode: 420
            items:
              - key: ticketing.yaml
                path: config.yaml
            secretName: itsm
