- name: Set timezone
  shell: "timedatectl set-timezone Asia/Shanghai"

- name: Set hostname
  shell: "hostname -F /etc/hostname"

- name: update /etc/hostname
  template: src=templates/hostname dest=/etc/hostname owner=root group=root mode=0644 unsafe_writes=yes

- name: Update /etc/hosts
  template: src=templates/hosts dest=/etc/hosts owner=root group=root mode=0644 force=yes unsafe_writes=yes

- name: Set systemd-resolved and set static DNS
  include_tasks: setup-systemd-resolved.yml

- name: Install packages
  script: files/install-packages.sh
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")

- name: Include Privoxy sub task for SOCKS5 to HTTP proxy (optional)
  include_tasks: setup-privoxy.yml
  when: privoxy.enable | default(false)

#- name: Include GPU Configuration
#  include_tasks: include_gpu.yaml
#  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
#  tags: 
#    - k3s
#    - gpu
#    - nvidia

#- name: enable ip_forward
#  shell: 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf; echo "net.ipv4.conf.all.proxy_arp = 1" >> /etc/sysctl.conf ; sysctl -p /etc/sysctl.conf'


#- name: Install packages
#  shell: "yum makecache && yum install -y audit container-selinux"
#  when: (ansible_facts['distribution'] != "Ubuntu") or (ansible_facts['distribution'] != "Debian")
