[package]
name = "my_rust_server"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web  = "4.0.0"
actix-cors = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
