- name: Setup DNAT rules
  hosts: ingress-nodes
  become: yes
  gather_facts: no
  vars:
    overlay_config_path: "{{ playbook_dir }}/../../config/sit/vpn-overlay.yaml"
  roles:
    - role: setup-dnat
