- name: Run infrastructure setup
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    overlay_config_path: "{{ playbook_dir }}/../../config/sit/vpn-overlay.yaml" 
  roles:
    - vhosts/vpn-overlay/vxlan/hub
