- name: Setup WireGuard for site
  hosts: all
  become: true
  vars:
    overlay_config_path: "{{ playbook_dir }}/../../config/sit/vpn-overlay.yaml"
    overlay_keys_path: "{{ playbook_dir }}/../../config/sit/vpn-keys.yaml"
  roles:
    - vhosts/vpn-overlay/wireguard/site
