- name: Setup WireGuard for site
  hosts: overlay_sites
  become: true
  vars:
    overlay_config_path: "config/sit/vpn-overlay.yaml"
    overlay_keys_path: "config/sit/vpn-keys.yaml"
  roles:
    - vhosts/vpn-overlay/wireguard/site
