network:
  vpcs:
    - name: lz-main-vpc
      cidr_block: 10.10.0.0/16
      description: Landing zone baseline VPC
      tags:
        env: shared
      vswitches:
        - name: lz-prod-subnet
          cidr_block: 10.10.1.0/24
          zone_id: cn-hangzhou-h
          tags:
            env: prod
        - name: lz-test-subnet
          cidr_block: 10.10.2.0/24
          zone_id: cn-hangzhou-h
          tags:
            env: test
