---
- name: 加载 overlay 配置
  set_fact:
    overlay_data: "{{ lookup('file', overlay_config_path) | from_yaml }}"

- name: 加载密钥配置
  set_fact:
    overlay_keys: "{{ lookup('file', overlay_keys_path) | from_yaml }}"

- name: 提取当前节点信息（作为 current）
  set_fact:
    current_node: "{{ (overlay_data.sites + overlay_data.hubs) | selectattr('name', 'equalto', inventory_hostname) | list | first }}"
    current_key: "{{ overlay_keys.keys | selectattr('name', 'equalto', inventory_hostname) | list | first }}"

- name: 提取对端 peer 节点信息
  set_fact:
    peer_node: "{{ (overlay_data.sites + overlay_data.hubs) | selectattr('name', 'equalto', current_node.wireguard_peer) | list | first }}"
    peer_key: "{{ overlay_keys.keys | selectattr('name', 'equalto', current_node.wireguard_peer) | list | first }}"

- name: 生成 WireGuard 参数
  set_fact:
    current_wg_ip: "{{ current_node.wg_ip }}"
    peer_allowed_ips: "{{ peer_node.wg_ip }}/32"
    peer_endpoint: "{{ peer_node.public_ip }}:{{ overlay_data.hub_port | default(51820) }}"

- name: 渲染 wg0.conf
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  become: true

- name: 启用并启动 wg-quick@wg0
  systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
  become: true
