firewall_rules:
  - name: allow-ssh-web
    enabled: true
    vpc_name: dev-vpc-1
    source_ranges: ["0.0.0.0/0"]
    egress_ranges: ["10.0.0.0/16"]
    allow:
      - protocol: tcp
        ports: ["22", "80", "443"]

  - name: allow-default-inbound
    enabled: true
    vpc_name: dev-vpc-2
    description: Allow ICMP, SSH, and VXLAN from all sources
    source_ranges: ["0.0.0.0/0"]
    allow:
      - protocol: icmp
      - protocol: tcp
        ports: ["22"]
      - protocol: udp
        ports: ["4789"]
