# 基础网络参数
wg_network: 172.16.0.0/16
bridge_network: 10.253.0.0/16
vxlan_id: 100
hub_port: 51820

# 全局功能开关
features:
  enable_vless: true               # 是否通过 VLESS 中转 WG 流量
  enable_multi_hub: true           # 是否支持多 Hub 架构（false 则为单 Hub star 架构）
  enable_vxlan_between_sits: true  # 是否开启 vxlan 桥接（站点接入 Hub）
  enable_vxlan_between_hubs: true  # 是否开启 Hub 之间的 VXLAN Mesh
  only_wireguard: false            # 若为 true，仅使用 WireGuard 点对点，忽略 gretap/vxlan

# WireGuard Hub 节点配置
hubs:
  - name: cn-hub
    interface: eth0
    public_ip: 1.15.155.245
    wg_ip: 172.30.0.1
    br_ip: 10.253.253.1
    local_ip: 172.30.0.1
    remote_ip: 172.31.0.10
    xray:
      uuid: "18d270a9-533d-4b13-b3f1-e7f55540a9b2"
      relay_address: "global-proxy.onwalk.net"
      relay_port: '51820'
      remote_domain: "global-proxy.onwalk.net"
      cert_path: "/etc/ssl/onwalk.net.pem"
      key_path: "/etc/ssl/onwalk.net.key"
    wireguard_peer:
      - master-1
      - slave-1
      - agent-1
      - agent-1

  - name: global-hub
    interface: ens5
    public_ip: 1.15.155.245
    wg_ip: 172.31.0.1
    br_ip: 10.253.253.2
    local_ip: 172.31.0.1
    remote_ip: 172.30.0.1
    xray:
      uuid: "18d270a9-533d-4b13-b3f1-e7f55540a9b2"
      cert_path: "/etc/ssl/onwalk.net.pem"
      key_path: "/etc/ssl/onwalk.net.key"
      relay_address: "cn-proxy.onwalk.net"
      relay_port: '51820'
      remote_domain: "cn-proxy.onwalk.net"
    wireguard_peer:
      - master-1
      - slave-1 
      - agent-1 
      - agent-1 
    uuid: ""
    remote_domain: "global-proxy.onwalk.net"
    cert_path: "/etc/ssl/onwalk.net.pem"
    key_path: "/etc/ssl/onwalk.net.key"

  - name: tky-proxy
    interface: eth0
    wg_ip: 172.30.0.1
    br_ip: 10.253.253.1
    local_ip: 172.30.0.1
    remote_ip: 172.31.0.1
    xray:
      uuid: "18d270a9-533d-4b13-b3f1-e7f55540a9b2"
      remote_domain: "global-proxy.onwalk.net"
      cert_path: "/etc/ssl/onwalk.net.pem"
      key_path: "/etc/ssl/onwalk.net.key"

  - name: us-proxy
    interface: eth0
    wg_ip: 172.30.0.1
    br_ip: 10.253.253.1
    local_ip: 172.30.0.1
    remote_ip: 172.31.0.1
    xray:
      uuid: "18d270a9-533d-4b13-b3f1-e7f55540a9b2"
      remote_domain: "global-proxy.onwalk.net"
      cert_path: "/etc/ssl/onwalk.net.pem"
      key_path: "/etc/ssl/onwalk.net.key"

  - name: ca-proxy
    interface: eth0
    wg_ip: 172.30.0.1
    br_ip: 10.253.253.1
    local_ip: 172.30.0.1
    remote_ip: 172.31.0.1
    xray:
      uuid: "18d270a9-533d-4b13-b3f1-e7f55540a9b2"
      remote_domain: "global-proxy.onwalk.net"
      cert_path: "/etc/ssl/onwalk.net.pem"
      key_path: "/etc/ssl/onwalk.net.key"

# 各个站点定义
sites:
  - name: master-1
    interface: ens5
    public_ip: 1.15.155.245
    allowed_ips: "172.16.0.0/16"
    wireguard_peer: hub-1
    br_ip: 10.253.253.2
    wg_ip: 172.16.0.10
    local_ip: 172.16.0.10
    remote_ip: 172.16.0.11
    vless:
      enabled: false
      uuid: "11111111-1111-1111-1111-111111111111"
      transport: ws
      tls: true
      path: /wg

  - name: slave-1
    interface: ens5
    public_ip: 1.15.155.245
    wireguard_peer: hub-1
    allowed_ips: "172.16.0.0/16"
    br_ip: 10.253.253.3
    wg_ip: 172.16.0.11
    local_ip: 172.16.0.11
    remote_ip: 172.16.0.10
    vless:
      enabled: false  # 此节点不通过 VLESS，直接访问 Hub

  - name: site_c
    public_ip: 1.15.155.245
    wg_ip: 10.100.1.2
    br_ip: 172.16.1.2
    hub: hub2
    public_ip: c.example.com
    vless:
      enabled: true
      endpoint: vless-c.example.com
      uuid: "33333333-3333-3333-3333-333333333333"
      transport: ws
      tls: true
      path: /xray

  - name: deepflow-demo
    interface: wlp0s20f3
    public_ip: 172.30.0.10
    wg_ip: 172.30.0.10
    br_ip: 10.253.253.2
    local_ip: 172.30.0.10
    remote_ip: 172.30.0.1
    wireguard_peer: cn-hub
    allowed_ips: "172.30.0.0/16"
    vless:
      enabled: true
      endpoint: vless-c.example.com
      uuid: "33333333-3333-3333-3333-333333333333"
      transport: ws
      tls: true
      path: /xray
