name: Multi-Cloud Landing Zone Baseline

on:
  workflow_dispatch:
    inputs:
      deploy_action:
        description: "Deployment action to execute"
        type: choice
        options:
          - init
          - create
          - migrate
          - upgrade
          - backup
          - restore
          - destroy
        default: upgrade
      deploy_dry_run:
        description: "Run deployment steps in dry-run mode"
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  run-baseline:
    name: Trigger baseline workflow (${{ matrix.provider }})
    strategy:
      matrix:
        include:
          - provider: Alicloud
            config: config/alicloud/
            workflow: iac-pipeline-alicloud-landingzone-baseline.yaml
            action: output
          - provider: AWS
            config: config/aws-global/
            workflow: iac-pipeline-aws-landingzone-baseline.yaml
            action: output
          - provider: Vultr
            config: config/vultr/
            workflow: iac-pipeline-vultr-landingzone-baseline.yaml
            action: output
    uses: ./.github/workflows/${{ matrix.workflow }}
    with:
      deploy_action: ${{ matrix.action || inputs.deploy_action }}
      deploy_dry_run: ${{ inputs.deploy_dry_run }}
      config_path: ${{ matrix.config }}
    secrets: inherit

  pulumi-up:
    name: Pulumi up (${{ matrix.provider }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - provider: AWS
            stack: svc-design/aws-lz-us-east-1-dev
            region: us-east-1
          - provider: Alicloud
            stack: svc-design/alicloud-lz-cn-hangzhou-dev
            region: cn-hangzhou
          - provider: Vultr
            stack: svc-design/vultr-lz-global-dev
            region: global
    steps:
      - name: Pulumi up
        run: pulumi up --stack ${{ matrix.stack }} --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SK }}
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_AK }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SK }}
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
