name: Alicloud Landing Zone Baseline

on:
  push:
    paths:
      - 'iac_modules/pulumi/**'
      - 'config/alicloud/**'
      - '.github/workflows/iac-pipeline-alicloud-landingzone-baseline.yaml'
  workflow_dispatch:

env:
  PULUMI_CI: 'true'
  CONFIG_PATH: config/alicloud

jobs:
  preview:
    name: Preview baseline changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pulumi preview
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: alicloud/baseline-dev
          work-dir: iac_modules/pulumi
        env:
          ALICLOUD_ACCESS_KEY_ID: ${{ secrets.ALICLOUD_ACCESS_KEY_ID }}
          ALICLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALICLOUD_ACCESS_KEY_SECRET }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  apply:
    name: Apply to production stack
    needs: preview
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: alicloud/baseline-prod
          work-dir: iac_modules/pulumi
        env:
          ALICLOUD_ACCESS_KEY_ID: ${{ secrets.ALICLOUD_ACCESS_KEY_ID }}
          ALICLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALICLOUD_ACCESS_KEY_SECRET }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
