name: Alicloud Landing Zone Baseline

on:
  push:
    paths:
      - 'iac_modules/pulumi/**'
      - 'config/alicloud/**'
      - '.github/workflows/iac-pipeline-alicloud-landingzone-baseline.yaml'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_action:
        description: "Deployment action to execute"
        type: choice
        options:
          - init
          - migrate
          - upgrade
          - backup
          - restore
          - destroy
        default: upgrade
      deploy_dry_run:
        description: "Run deployment steps in dry-run mode"
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      config_path:
        description: "Configuration directory path"
        required: false
        type: string
        default: config/alicloud
  workflow_call:
    inputs:
      deploy_action:
        required: false
        type: string
        default: upgrade
      deploy_dry_run:
        required: false
        type: string
        default: 'true'
      config_path:
        required: false
        type: string
        default: config/alicloud
    secrets:
      ALICLOUD_ACCESS_KEY:
        required: true
      ALICLOUD_SECRET_KEY:
        required: true
      ALICLOUD_REGION:
        required: false
      PULUMI_ACCESS_TOKEN:
        required: true

env:
  PULUMI_CI: 'true'
  CONFIG_PATH: ${{ inputs.config_path || github.event.inputs.config_path || 'config/alicloud' }}
  DEPLOY_ACTION: ${{ inputs.deploy_action || github.event.inputs.deploy_action || 'upgrade' }}
  DEPLOY_DRY_RUN: ${{ inputs.deploy_dry_run || github.event.inputs.deploy_dry_run || 'true' }}

jobs:
  preview:
    name: Preview Alicloud baseline changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pulumi preview
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: alicloud/landingzone-baseline-dev
          work-dir: iac_modules/pulumi
        env:
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}
          ALICLOUD_REGION: ${{ secrets.ALICLOUD_REGION }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  apply:
    name: Apply to Alicloud production stack
    needs: preview
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_call'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: alicloud/landingzone-baseline-prod
          work-dir: iac_modules/pulumi
        env:
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}
          ALICLOUD_REGION: ${{ secrets.ALICLOUD_REGION }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  validation:
    name: Validate Alicloud baseline readiness
    needs: apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run baseline validation checks
        run: scripts/validation/validate-baseline.sh "Alicloud" "${{ env.CONFIG_PATH }}" "iac_modules/pulumi"

  delivery:
    name: Deliver Alicloud baseline rollout notifications
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify stakeholders
        run: scripts/notifications/notify-baseline-delivery.sh
