---
- name: Restart xray service
  systemd:
    name: xray.service
    state: restarted
    enabled: yes

- name: Restart xray-tproxy service
  systemd:
    name: xray-tproxy.service
    state: restarted
    enabled: yes
